//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Actividad_Integradora_7_Problema_3.NumeroALetrasServicio {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NumeroALetrasServicio.NumerosALetrasServiceSoap")]
    public interface NumerosALetrasServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento valor del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LetrasANumeros", ReplyAction="*")]
        Actividad_Integradora_7_Problema_3.NumeroALetrasServicio.LetrasANumerosResponse LetrasANumeros(Actividad_Integradora_7_Problema_3.NumeroALetrasServicio.LetrasANumerosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LetrasANumeros", ReplyAction="*")]
        System.Threading.Tasks.Task<Actividad_Integradora_7_Problema_3.NumeroALetrasServicio.LetrasANumerosResponse> LetrasANumerosAsync(Actividad_Integradora_7_Problema_3.NumeroALetrasServicio.LetrasANumerosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LetrasANumerosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LetrasANumeros", Namespace="http://tempuri.org/", Order=0)]
        public Actividad_Integradora_7_Problema_3.NumeroALetrasServicio.LetrasANumerosRequestBody Body;
        
        public LetrasANumerosRequest() {
        }
        
        public LetrasANumerosRequest(Actividad_Integradora_7_Problema_3.NumeroALetrasServicio.LetrasANumerosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LetrasANumerosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string valor;
        
        public LetrasANumerosRequestBody() {
        }
        
        public LetrasANumerosRequestBody(string valor) {
            this.valor = valor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LetrasANumerosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LetrasANumerosResponse", Namespace="http://tempuri.org/", Order=0)]
        public Actividad_Integradora_7_Problema_3.NumeroALetrasServicio.LetrasANumerosResponseBody Body;
        
        public LetrasANumerosResponse() {
        }
        
        public LetrasANumerosResponse(Actividad_Integradora_7_Problema_3.NumeroALetrasServicio.LetrasANumerosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LetrasANumerosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LetrasANumerosResult;
        
        public LetrasANumerosResponseBody() {
        }
        
        public LetrasANumerosResponseBody(string LetrasANumerosResult) {
            this.LetrasANumerosResult = LetrasANumerosResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NumerosALetrasServiceSoapChannel : Actividad_Integradora_7_Problema_3.NumeroALetrasServicio.NumerosALetrasServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NumerosALetrasServiceSoapClient : System.ServiceModel.ClientBase<Actividad_Integradora_7_Problema_3.NumeroALetrasServicio.NumerosALetrasServiceSoap>, Actividad_Integradora_7_Problema_3.NumeroALetrasServicio.NumerosALetrasServiceSoap {
        
        public NumerosALetrasServiceSoapClient() {
        }
        
        public NumerosALetrasServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NumerosALetrasServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NumerosALetrasServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NumerosALetrasServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Actividad_Integradora_7_Problema_3.NumeroALetrasServicio.LetrasANumerosResponse Actividad_Integradora_7_Problema_3.NumeroALetrasServicio.NumerosALetrasServiceSoap.LetrasANumeros(Actividad_Integradora_7_Problema_3.NumeroALetrasServicio.LetrasANumerosRequest request) {
            return base.Channel.LetrasANumeros(request);
        }
        
        public string LetrasANumeros(string valor) {
            Actividad_Integradora_7_Problema_3.NumeroALetrasServicio.LetrasANumerosRequest inValue = new Actividad_Integradora_7_Problema_3.NumeroALetrasServicio.LetrasANumerosRequest();
            inValue.Body = new Actividad_Integradora_7_Problema_3.NumeroALetrasServicio.LetrasANumerosRequestBody();
            inValue.Body.valor = valor;
            Actividad_Integradora_7_Problema_3.NumeroALetrasServicio.LetrasANumerosResponse retVal = ((Actividad_Integradora_7_Problema_3.NumeroALetrasServicio.NumerosALetrasServiceSoap)(this)).LetrasANumeros(inValue);
            return retVal.Body.LetrasANumerosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Actividad_Integradora_7_Problema_3.NumeroALetrasServicio.LetrasANumerosResponse> Actividad_Integradora_7_Problema_3.NumeroALetrasServicio.NumerosALetrasServiceSoap.LetrasANumerosAsync(Actividad_Integradora_7_Problema_3.NumeroALetrasServicio.LetrasANumerosRequest request) {
            return base.Channel.LetrasANumerosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Actividad_Integradora_7_Problema_3.NumeroALetrasServicio.LetrasANumerosResponse> LetrasANumerosAsync(string valor) {
            Actividad_Integradora_7_Problema_3.NumeroALetrasServicio.LetrasANumerosRequest inValue = new Actividad_Integradora_7_Problema_3.NumeroALetrasServicio.LetrasANumerosRequest();
            inValue.Body = new Actividad_Integradora_7_Problema_3.NumeroALetrasServicio.LetrasANumerosRequestBody();
            inValue.Body.valor = valor;
            return ((Actividad_Integradora_7_Problema_3.NumeroALetrasServicio.NumerosALetrasServiceSoap)(this)).LetrasANumerosAsync(inValue);
        }
    }
}
